{
  "name": "catch-errors",
  "version": "0.1.0",
  "description": "A high-order function to catch errors from promises.",
  "author": "Roberto Achar <robertoachar@gmail.com>",
  "homepage": "https://github.com/robertoachar/catch-errors#readme",
  "keywords": [
    "node",
    "promises",
    "async",
    "await",
    "catch",
    "error",
    "errors"
  ],
  "main": "src/index.js",
  "files": [
    "src"
  ],
  "scripts": {
    "lint": "eslint src/**/*.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/robertoachar/catch-errors.git"
  },
  "bugs": {
    "url": "https://github.com/robertoachar/catch-errors/issues"
  },
  "dependencies": {},
  "devDependencies": {
    "eslint": "4.7.2",
    "node-fetch": "1.7.3"
  },
  "license": "MIT"
}
